version:  '3.8'
services:
  codeserver2:
      image: linuxserver/code-server:latest
      restart: unless-stopped
      hostname: codeserver2
      #shm_size: 16gb
      #network_mode: "bridge"
      networks:
        - testNet
      volumes:
        - config:/config

      environment:
        - PUID=1000
        - PGID=100
        - TZ=Asia/Seoul
        - PASSWORD=12341234!
        - SUDO_PASSWORD=12341234!
        - PROXY_DOMAIN='43.201.197.216'
      ports:
        - 8444:8443
        - 5006:5006  
      #deploy:
      #  resources:
      #    limits:
      #      memory: 22G
            

volumes:
  config:
  
networks:
  testNet:
    external: true


