version: "3"
services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    #user: "${UID}:${GID}" 
    user: root
    networks:
      - testNet
    ports:
      - 9190:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=90d # 90일보다 오래된 metrics는 삭제
      - --storage.tsdb.retention.size=10GB # 10GB를 넘을 시 오래된 metrics 삭제
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/proemtheus/consoles
      - --web.enable-admin-api

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    #user: "${UID}:${GID}"
    user: root
    depends_on:
      - prometheus    
    networks:
      - testNet
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=grafana # grafana 사용자 이름
      - GF_SECURITY_ADMIN_PASSWORD=grafana # grafana 사용자 비밀번호
      - GF_USERS_ALLOW_SIGN_UP=false


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100:9100
    ports:
      - 9100:9100
    networks:
      - testNet

networks:
  testNet:
    external: true

    #volumes:
    #  grafana-data:
    #  prometheus-data:
