global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # Evaluate rules every 15 seconds.

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'master'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'slave1'
    static_configs:
      - targets: ['172.31.10.109:9100']
  - job_name: 'slave2'
    static_configs:
      - targets: ['172.31.15.3:9100']
  - job_name: 'airflow'
    static_configs:
            #- targets: ['airflow-webserver:8080']
      - targets: ['statsd-exporter:9102']  
